version: '3'

services:

  rabbitmq:
    # build:
    #   context: .
    #   dockerfile: Dockerfile-rabbitmq
    image: dfang/rabbitmq-cluster
    environment:
      - RABBITMQ_ERLANG_COOKIE=abcdefghjklmnopqrstuvw
    restart: always
    # depends_on:
    #   - rabbitmq1
    # deploy:
    #   replicas: 2
    #   restart_policy: 
    #     condition: on-failure
    #     delay: 5s
    #     window: 120s
    #     max_attempts: 3
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq:/var/lib/rabbitmq
      # - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    # ports:
    #   - 15673:15672

  consul:
    image: consul
    ports:
      - 8500:8500

  # haproxy:
  #   image: haproxy:1.7
  #   volumes:
  #     - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    

  haproxy:
    image: dfang/haproxy-consul
    command: "consul-template -config=/tmp/haproxy.hcl -consul-addr=consul:8500 -log-level=info"
    environment:
      - CONSUL_URL=consul:8500
    ports:
      - 1936:1936
      - 15672:15672
      - 1883:1883
    # volumes:
    #   - /opt/haproxy:/tmp

  # linkerd-tcp:
  #   image: linkerd/linkerd-tcp:0.1.1
  #   ports:
  #   - 9992:9992
  #   volumes:
  #   - ./linkerd-tcp.yml:/config.yml:ro
  #   command:
  #   - "/config.yml"

  # namerd:
  #   image: buoyantio/namerd:1.4.6
  #   ports:
  #   - 4180:4180
  #   - 9991:9991
  #   volumes:
  #   - ./namerd.yml:/io.buoyant/namerd/config.yml:ro
  #   - ./disco:/disco
  #   command:
  #   - "/io.buoyant/namerd/config.yml"

volumes:
  rabbitmq:
    driver: local