version: '3'

services:
  rabbitmq1:
    build:
      context: .
      dockerfile: Dockerfile-rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=abcdefghjklmnopqrstuvw
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq:/var/lib/rabbitmq
      # - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    ports:
      - 15672:15672

  rabbitmq2:
    build:
      context: .
      dockerfile: Dockerfile-rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=abcdefghjklmnopqrstuvw
    depends_on:
      - rabbitmq1
    restart: always
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq:/var/lib/rabbitmq
      # - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
    # ports:
    #   - 15673:15672

  consul:
    image: consul
    ports:
      - 8500:8500

volumes:
  rabbitmq:
    driver: local