FROM rabbitmq:3.7-management
RUN rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_mqtt rabbitmq_federation_management rabbitmq_peer_discovery_consul

EXPOSE 5672 15672 25672 4369 9100 9101 9102 9103 9104 9105



